version: '3'
x-aws-vpc: "vpc-0190c145d43d6537b"
services: 
  web:
    environment:
      - CI=true
    image: danielpich/docker-react:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:3000"
    command: ["npm", "run", "start"]