version: '3'
x-aws-vpc: "vpc-0190c145d43d6537b"
services: 
  web:
    environment:
      - CI=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    command: ["npm", "run", "test"]